#!/bin/bash
source .github/hooks/loading.sh
trap 'end_animation 1' ERR
trap exit_early SIGINT

exit_early() {
  end_animation 0xBEEFBEEF
  exit 0
}


beg_animation "running compiler"
pnpm -s build
end_animation


beg_animation "running eslint"
pnpm -s lint --quiet
end_animation


beg_animation "running prettier"
pnpm -s format --log-level warn
end_animation


beg_animation "running unit tests"
pnpm -s "test:cov" --silent \
  --reporters="<rootDir>/test/config/reporter.js"
end_animation
git add "resources/badge-coverage.svg"
git add "resources/badge-version.svg"


beg_animation "running integration tests"
AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1 \
  pnpm -s "test:int" --silent \
    --reporters="<rootDir>/test/config/reporter.js"
end_animation
