#!/bin/sh
set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && echo "no changes staged for commit" && exit 0

npx ts-node .github/hooks/pre-commit.ts $FILES
